chore: add cargo udeps

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -14,5 +14,12 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+# Run cargo udeps
+cargo +nightly udeps
+if [ $? -ne 0 ]; then
+  echo "Error: Some dependencies are unused."
+  exit 1
+fi
+
 echo "All checks passed. Proceeding with the commit."
 exit 0
